# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31ae0a14812d3c1dab0e9946357eb3a4406b84defc6c092fe7a93be9a78af9e862b80963e1f69c5d6e93a51b0a0328ee930c7f79fb0db9453c791d2d5d12e11e

test:
  secret_key_base: ed11a392d813c3478a2e46fa40f89ecb8d393eb20059999d6c4180509697659ca5aae29ef7c4be5b552f111731cb8e975ab82966fbd3bab482210cb4a2bd15f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
